const ROLE ={
  USER: 'PERSONAL_ROLE',
  ADMIN : 'ADMIN_ROLE',
  BUSSINESS : 'BUSSINESS_ROLE',
}

const BLOCKCHAIN ={
  EOS: 'eos',   
  TRON: 'tron', 
  CARDANO: 'ada', 
  WAVES: 'waves', 
  NEO: 'neo', 
  ETHEREUM: 'eth', 
  BINANCESMARTCHAIN: 'bsc',
  BITCOIN: 'btc', 
}

const MINUTES_CODE = {
  MINUTES: 5
}

const STATUS = {
  PENDENT: 1,
  CANCEL: 2,
  TIMEOUT: 3,
  SUCESSFULL: 4,
  INCOMPLETE: 5,
  ERROR:6
}

const BLOCKCHAIN_DEFAULT =['bsc','tron'];

const EMAIL_TEMPLATE = {  
  SIGNUP:{
    ES:'<!doctype html><html lang="en"><head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> <meta name="theme-color" content="#563d7c"><style>.padding-top{padding-top:1%}.lead{font-size:1.4em}</style></head><body> <main role="main"> <div class="container marketing"> <header> <div class="row"> <div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header> <div class="row featurette padding-top"> <div class="col-lg-12"><h2 class="featurette-heading">Registrado éxistosamente. </h2><br> <p class="lead">Felicitaciones <b>$user_replace</b> se ha registrado éxistosamente en Utopia .<br><br> Para activar su cuenta de usuario haga click en el enlace a continuación: <a href="$link">activar cuenta de usuario<a></p><br><hr><p class="lead">Saludos. El Equipo de Utopia </p></div></div></div></main> <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>',
    EN: '<!doctype html><html lang="en"> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> <meta name="theme-color" content="#563d7c"> <style>.padding-top{padding-top:1%}.lead{font-size:1.4em}</style></head> <body> <main role="main"> <div class="container marketing"> <header> <div class="row"> <div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header> <div class="row featurette padding-top"> <div class="col-lg-12"><br> <h2 class="featurette-heading">Signed up successfully! </h2><br> <p class="lead"> Congratulations! <b>$user_replace</b> has been registered successfully in the TovaExchangeplatform.<br><br> To activate your user account, click on this link: <a href="$link">activate user account <a> </p><br><br><hr><p class="lead">Greetings. The TovaExchange team.</p></div></div></div> </main> <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> </body></html>'
  },
  LOGINCODE:{
    ES:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"><meta name="theme-color" content="#563d7c"><style>.padding-top{padding-top:1%}.lead{font-size:1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Código de verificación.</h2><br><p class="lead">Hola <b>$user_name</b>.</p><p class="lead">Tú código de verificación para ingresar a tu cuenta de usuario es: <b>$code_generated</b>.</p><p class="lead">El código caducará en 5 minutos.</p><br><hr><p class="lead">Saludos. El Equipo de Utopia </p></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>',
    EN:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"><meta name="theme-color" content="#563d7c"><style>.padding-top{padding-top:1%}.lead{font-size:1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Access Code.</h2><br><p class="lead">Hello <b>$user_name</b>.</p><p class="lead">Your access code to sign in on your user account is: <b>$code_generated</b>.</p><p class="lead">The code will expire in 5 minutes.</p><br><hr><p class="lead">Greetings. The TovaExchange team.</p></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>'
  },
  PASWWORD_LOST:{
    ES:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" /><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" /><meta name="theme-color" content="#563d7c" /><style>.padding-top{padding-top:1%}.lead{font-size:1.4em}</style></head><body> <main role="main"><div class="container marketing"> <header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div> </header><div class="row featurette padding-top"><div class="col-lg-12"><br><h2 class="featurette-heading">Password recuperado.</h2><br><p class="lead">Querido usuario, hemos generado un nuevo password para usted, ingrese al sistema con él y cambielo editando su perfil.</p> <p class="lead">Password temporal: <b>$password_replace</b></p><br><hr><p class="lead">Saludos. El Equipo de Utopia </p></div></div></div> </main> <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> </body></html>',
    EN:'<!DOCTYPE html><html lang="en"> <head> <meta charset="utf-8"/> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/> <link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/> <meta name="theme-color" content="#563d7c"/> <style>.padding-top{padding-top:1%}.lead{font-size:1.4em}</style></head> <body> <main role="main"> <div class="container marketing"> <header> <div class="row"> <div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header> <div class="row featurette padding-top"> <div class="col-lg-12"><br> <h2 class="featurette-heading">Password recovered.</h2><br> <p class="lead">Dear user, we\'ve generated a new password for you, please enter in the system with it and change it in the profile section.</p><p class="lead">Temporary password: <b>$password_replace</b></p><br><hr><p class="lead">Greetings. The TovaExchange team.</p></div></div> </div> </main> <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> </body></html>'
  },
  CREATETRANSACTION:{
    ES:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"><meta name="theme-color" content="#563d7c"><style>.padding-top{padding-top:1%}.lead{font-size: 1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Transacción creada éxitosamente.</h2><br><p class="lead">Sr/a. $name se ha creado una transacción de pago con el identificador: <b>$id</b>.</p><p class="lead">Fecha de creación: <b>$date</b>.</p><p class="lead">Total a pagar: <b>$monto</b>.</p><p class="lead">Enviar: <b>$moneda</b> a la siguiente wallet: <b>$wallet</b></p><br><hr><p class="lead">Recuerde que tiene un tiempo limitado para enviar las monedas a la direccion de la wallet, de otra manera la transacción quedará anulada.</p><br></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>',
    EN: '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/><meta name="theme-color" content="#563d7c"/><style>.padding-top{padding-top: 1%;}.lead{font-size: 1.3em}		</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"/></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Transaction created successfully.</h2><br><p class="lead">A payment transaction with the identificator: <b>$id</b>. has been created</p><p class="lead">Date: <b>$date</b>.</p><p class="lead">Ammount to pay: <b>$monto</b>.</p><p class="lead">Send: <b>$moneda</b> to the next wallet: <b>$wallet</b></p><br><hr><p class="lead">Please rememeber that you have only $time minutes to send the coins to the wallet address, otherwise the transaction will be cancelled.</p></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>'
  },
  ANULATETRANSACTION:{
    ES:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/><meta name="theme-color" content="#563d7c"/><style>.padding-top{padding-top:1%}.lead{font-size: 1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"/></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Transacción anulada.</h2><br><p class="lead">Se ha anulado la transacción con el identificador <b>$id</b>.</p><p class="lead">Fecha de anulación: <b>$date</b>.</p><p class="lead">Total a pagar: <b>$total</b>.</p><p class="lead">Wallet: <b>$wallet</b></p><br><hr><p class="lead">La transacción fue anulada con el botón de anulación, por favor abstenerse de enviar alguna moneda a la dirección de la billetera mostrada.</p></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>',
    EN:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/><meta name="theme-color" content="#563d7c"/><style>.padding-top{padding-top: 1%;}.lead{font-size: 1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"/></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Transaction cancelled.</h2><br><p class="lead">The transaction identified by ID <b>$id</b> was cancelled.</p><p class="lead">Cancellation date: <b>$date</b>.</p><p class="lead">Ammount to pay: <b>$total</b>.</p><p class="lead">Wallet: <b>$wallet</b></p><br><hr><p class="lead">The transaction was cancelled with the cancellation button, please avoid sending any coin to the wallet address displayed.</p><br/></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>'
  },
  TIMEOUTTRANSACTION:{
    ES:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/><meta name="theme-color" content="#563d7c"/><style>.padding-top{padding-top: 1%;}.lead{font-size: 1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Transacción cancelada por falta de tiempo.</h2><br><p class="lead">Se ha cancelado la transacción con el identificador <b>$id.</b></p><p class="lead">Fecha de timeout: <b>$date</b>.</p><p class="lead">Total a pagar: <b>$total</b>.</p><p class="lead">Wallet: <b>$wallet</b></p><br><hr><p class="lead">La transacción fue cancelada por falta de tiempo, por favor abstenerse de enviar alguna moneda a la dirección de la billetera mostrada, en caso de que usted ya realizó el envío de las monedas pero no se ha procesado, por favor contactar con el equipo de soporte técnico.</p><br/></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>',
    EN: '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/><meta name="theme-color" content="#563d7c"/><style>.padding-top{padding-top: 1%;}.lead{font-size: 1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Transaction timed out.</h2><br><p class="lead">The transaction identified with ID <b>$id</b> has been cancelled.</p><p class="lead">Timeout date: <b>$date</b>.</p><p class="lead">Ammount to pay: <b>$total</b>.</p><p class="lead">Wallet: <b>$wallet</b></p><br><hr><p class="lead">The transaction timed out and was cancelled, please avoid sending any coin to the shown wallet, in case you already sent the coins but have not been yet processed, please contact with the technical support team.</p><br/></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>'
  },
  SUCCESSTRANSACTION:{
    ES:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" /><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" /><meta name="theme-color" content="#563d7c" /><style>.padding-top{padding-top:1%}.lead{font-size: 1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Felicitaciones transacción éxitosa.</h2><br><p class="lead">La transacción con el identificador <b>$id</b> se ha procesado de manera éxitosa.</p><p class="lead">Fecha de aprobación: <b>$date</b>.</p><p class="lead">Total pagado: <b>$coins</b>.</p><p class="lead">Wallet: <b>$wallet</b></p><br><hr><p class="lead">Saludos. El Equipo de Utopia </p></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>',
    EN:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/><meta name="theme-color" content="#563d7c"/><style>.padding-top{padding-top:1%}.lead{font-size: 1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Congratulations! Transaction successful.</h2><br><p class="lead">The transaction identified with ID <b>$id</b> has been processed successfully.</p><p class="lead">Date of approval: <b>$date</b>.</p><p class="lead">Ammount paid: <b>$coins</b>.</p><p class="lead">Wallet: <b>$wallet</b></p><br><hr><p class="lead">Greetings. The TovaExchange team.</p></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>'
  },
  INCOMPLETETRANSACTION:{
    ES:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/><meta name="theme-color" content="#563d7c"/><style>.padding-top{padding-top: 1%;}.lead{font-size: 1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"/></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Transacción incompleta.</h2><br><p class="lead">La transacción con el identificador <b>$id</b> se ha procesado de manera éxitosa, pero el pago enviado por usted está incompleto.</p><p class="lead">Fecha de procesamiento: <b>$date</b></p><p class="lead">Monedas solicitadas: <b>$coinrequest</b></p><p class="lead">Monedas enviadas: <b>$coinsent</b></p><p class="lead">Diferencia: <b><span style="color:red">$diffcoins</span></b></p><p class="lead">Wallet: <b>$wallet</b></p><br><hr><p class="lead">La transacción fue procesada éxitosamente, pero el pago ha quedado incompleto, por favor enviar el monto de la diferencia para su posterior procesamiento y culminar con la transacción.</p><br/></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>',
    EN:'<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/><meta name="theme-color" content="#563d7c"/><style>.padding-top{padding-top: 1%;}.lead{font-size: 1.4em}</style></head><body><main role="main"><div class="container marketing"><header><div class="row"><div class="col-sm-12 col-md-6 col-lg-6"><img src="https://toptoken.tech/images/banner-img.png" class="img-fluid"/></div></div></header><div class="row featurette padding-top"><div class="col-lg-12"><h2 class="featurette-heading">Transaction Incomplete.</h2><br><p class="lead">The transaction identified by ID <b>$id</b> was processed successfully but the payment sent is incomplete.</p><p class="lead">Processing date: <b>$date</b></p><p class="lead">Coins requested: <b>$coinrequest</b></p><p class="lead">Coins sent: <b></b>$coinsent</p><p class="lead">Difference: <b><span style="color:red">$diffcoins</span></b></p><p class="lead">Wallet: <b>$wallet</b></p><br><hr><p class="lead">The transaction was processed succesfully, however the payment was not completed, please send the ammount of the difference to complete the processing and finish the transaction.</p><br/></div></div></div><footer class="container"></footer></main><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script></body></html>'
  },
}

module.exports = {ROLE, BLOCKCHAIN,STATUS,EMAIL_TEMPLATE,MINUTES_CODE,BLOCKCHAIN_DEFAULT};